### ISSUE TITLE
ペットの餌なかなか集まらない問題

### ISSUE THREAD

**Issue by Aritake** [Aritake/habitica-develop#15]
タスク達成時のランダムで獲得できるペットの餌（種類もランダム）をタスクを達成すればランダムでいずれかの餌を獲得できるようにする

**Comment by hylian-flute** [comment]
この問題は二つに分割できる。一つ目はドロップ率の改善で、これは恐らく<code>website/common/script/fns/randomDrop.js</code>で計算されている。47行目の<code>chance = diminishingReturns(chance, 0.75);</code>がドロップ率だと思われるが、ここを1にしても確定ドロップにはならなかったので要検証。ドロップ確定後にアイテムが決定され、餌はドロップのうちの40%。
　二つ目は<a href="http://habitica.wikia.com/wiki/Drops#Drop-Cap">ドロップキャップ</a>の開放で、ドロップ率とは別に一日にドロップできるアイテムの個数には上限が設定されており、これを引き上げるかなくす必要がある。こちらを変更する方法はまだ不明。

**Comment by hylian-flute** [comment]
<code>website/common/script/fns/randomDrop.js</code>の47行目の<code>chance = diminishingReturns(chance, 0.75);</code>の部分を<code>chance = Math.pow(diminishingReturns(chance, 0.75), 0);</code>に変更して確率を0乗することで100%ドロップするようにしました。<code>Math.pow</code>の第二引数を1に近づけると元のドロップ率に近づくので調整してください。
また、65行目の<code>return</code>をコメントアウトすることで、ドロップキャップに到達している場合に関数を終了する処理を無効にしました。これで一日にいくつでもアイテムをドロップできるようになります。
今回は変更していませんが、71行目と84行目のif文の条件式の右辺を変えることで、ドロップアイテムの餌率を変更することができるはずです。

**Comment by Aritake** [comment]
ありがとうございます。試してみます。
